### ISSUE TITLE
SAmple Code

### ISSUE THREAD

**Issue by xumes** [CognosExt/jcognos#3]
Hello,

Do you have any sample code? I am trying to connect to my Cognos server but I did not understood the parameters I need to pass.

Any help is appreciated.

Thanks in advance,
Reginaldo Santos

**Comment by xumes** [comment]
Here is the code I have developed so far.

```
const jCognos = require('jcognos')

const url = 'https://zcogwass1.boulder.ibm.com/transform/cognitive/bi'

jCognos.getCognos(url).then(res => {
    console.log('ready for login', res)
})

```

and here, the error on console:

```
reginaldos-mbp:cognos reginaldosantos$ node cogplug.js 
(node:11201) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): XMLHttpRequest is not defined
(node:11201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by batje** [comment]
Your code is correct, my rollup config was wrong. Fixed this in a new release. npm update should fix this for you.

**Comment by batje** [comment]
Hi Xumes, did that work for you? Just curious.

**Comment by xumes** [comment]
Hi, I am using another library, will try again using yours and I'll let you know if it is working now.
